# Reference:
#   https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cloud-controller-manager
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: cloud-controller-manager
  name: cloud-controller-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: cloud-controller-manager
    spec:
      serviceAccountName: cloud-controller-manager
      containers:
        - name: cloud-controller-manager
          image: k8s.gcr.io/cloud-controller-manager:v1.14.6
          command:
            - /usr/local/bin/cloud-controller-manager
            - --cloud-provider=aws
            - --leader-elect=true
            - --use-service-account-credentials
            - --allocate-node-cidrs=true
            - --configure-cloud-routes=true
            - --cluster-cidr=172.17.0.0/16
            # Reference:
            #   https://kubernetes.io/docs/reference/command-line-tools-reference/cloud-controller-manager/
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: certificates
      volumes:
        - name: certificates
          hostPath:
            path: /etc/ssl/certs
            type: Directory

      tolerations:

        # this is required so CCM can bootstrap itself
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule

        # this is to have the daemonset runnable on master nodes the taint may
        # vary depending on your cluster setup
        - key: node-role.kubernetes.io/master
          effect: NoSchedule

      # this is to restrict CCM to only run on master nodes the node selector
      # may vary depending on your cluster setup
      nodeSelector:
        node-role.kubernetes.io/master: "true"
