apiVersion: v1
kind: Namespace
metadata:
  name: gemini
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: gemini
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: gemini
  name: upnl.org-uploads
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  presistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /dev/sdf
    fsType: ext4
