apiVersion: v1
kind: Namespace
metadata:
  name: helix
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: helix
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.3-alpine
        volumeMounts:
        - name: db
          mountPath: /var/lib/postgresql/data
        envFrom:
        - secretRef:
            name: env
      volumes:
      - name: db
        hostPath:
          path: /srv/helix/postgres/data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: helix
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: helix
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        envFrom:
        - secretRef:
            name: env
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: helix
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: helix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: helix
        image: ghcr.io/upnl/helix:2020-01-25
        volumeMounts:
        - name: upload
          mountPath: /app/fossil/upload
        envFrom:
        - secretRef:
            name: env
      volumes:
        - name: upload
          hostPath:
            path: /srv/helix/upload
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: helix
  namespace: helix
spec:
  selector:
    app: web
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 54322
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helix
  namespace: helix
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'true'
    ingress.kubernetes.io/force-hsts: "true"
    ingress.kubernetes.io/hsts-max-age: "15778800"
    ingress.kubernetes.io/hsts-include-subdomains: "false"
spec:
  tls:
  - hosts: ['helix.upnl.org']
    secretName: helix-cert
  rules:
  - host: helix.upnl.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helix
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helix-cert
  namespace: helix
spec:
  secretName: helix-cert
  dnsNames:
  - helix.upnl.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
