apiVersion: v1
kind: Namespace
metadata:
  name: pokemon-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pokemon-db
  namespace: pokemon-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-db
  namespace: pokemon-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-db
  template:
    metadata:
      labels:
        app: pokemon-db
    spec:
      containers:
        - name: flask
          image: pokemon-db:2019-09-23
          ports:
            - containerPort: 54323
          volumeMounts:
            - name: pokemon-db-sqlite-db
              mountPath: /app/pokemon/db/
      volumes:
        - name: pokemon-db-sqlite-db
          persistentVolumeClaim:
            claimName: pokemon-db
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-db
  namespace: pokemon-db
spec:
  selector:
    app: pokemon-db
  ports:
    - protocol: TCP
      port: 54323
      targetPort: 54323
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pokemon-db
  namespace: pokemon-db
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-hsts: "true"
    ingress.kubernetes.io/hsts-max-age: "15778800"
    ingress.kubernetes.io/hsts-include-subdomains: "false"
spec:
  tls:
    - hosts: ['pokemon.upnl.org']
      secretName: pokemon-db
  rules:
    - host: pokemon.upnl.org
      http:
        paths:
          - backend:
              serviceName: pokemon-db
              servicePort: 54323
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: pokemon-db
  namespace: pokemon-db
spec:
  secretName: pokemon-db
  dnsNames:
    - pokemon.upnl.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
